name: SimpleRegionMarket
version: 1.5.1
author: theZorro266
website: http://dev.bukkit.org/server-mods/simple-region-market/
dev-url: http://dev.bukkit.org/server-mods/simple-region-market/
main: com.thezorro266.simpleregionmarket.SimpleRegionMarket
depend: ['WorldGuard']
softdepend: ['Multiverse-Core']

commands:
  regionmarket:
    description: Using Simple Region Market
    aliases: rm
    usage: /regionmarket ? | list | maxregions | lang

permissions:
  simpleregionmarket.*:
    description: Admin commands, Buying/Selling regions
    children:
      simpleregionmarket.admin: true
      simpleregionmarket.buy: true
      simpleregionmarket.sell: true
      simpleregionmarket.rent: true
      simpleregionmarket.create: true
  simpleregionmarket.admin:
    default: op
  simpleregionmarket.buy:
    default: false
  simpleregionmarket.sell:
    default: false
  simpleregionmarket.rent:
    default: false
  simpleregionmarket.create:
    default: false