name: SimpleRegionMarket
version: 1.7.8
author: theZorro266
website: http://srm.theZorro266.com/
main: com.thezorro266.simpleregionmarket.SimpleRegionMarket
depend: ['WorldGuard']
softdepend: ['Vault', 'ChestShop']

commands:
  regionmarket:
    description: Using Simple Region Market
    aliases: rm
    usage: /regionmarket limits | list | version

permissions:
  simpleregionmarket.admin:
    description: Admin permissions
  simpleregionmarket.addowner:
    description: Add owner to own region
  simpleregionmarket.addmember:
    description: Add member to own region
  simpleregionmarket.*:
    description: Permission for buy/sell/rent/let
    children:
      simpleregionmarket.buy: true
      simpleregionmarket.sell: true
      simpleregionmarket.rent: true
      simpleregionmarket.create: true
  simpleregionmarket.buy:
    description: Buying regions
  simpleregionmarket.sell:
    description: Selling regions
  simpleregionmarket.rent:
    description: Renting rooms
  simpleregionmarket.let:
    description: Letting rooms
