name: SimpleRegionMarket
version: 1.8-pre2
author: theZorro266
website: http://srm.thezorro266.com
main: com.thezorro266.simpleregionmarket.SimpleRegionMarket
depend: ['WorldGuard']
softdepend: ['Vault']

commands:
  regionmarket:
    description: Using Simple Region Market
    aliases: rm
    usage: /regionmarket limits | list | version

permissions:
  simpleregionmarket.*:
    description: Permission for buy/sell/rent/let
    children:
      simpleregionmarket.admin: false
      simpleregionmarket.buy: true
      simpleregionmarket.sell: true
      simpleregionmarket.rent: true
      simpleregionmarket.create: true
  simpleregionmarket.admin:
    description: Admin permissions
  simpleregionmarket.buy:
    description: Buying regions
  simpleregionmarket.sell:
    description: Selling regions
  simpleregionmarket.rent:
    description: Renting rooms
  simpleregionmarket.let:
    description: Letting rooms
