name: SimpleRegionMarket
version: 1.4
author: theZorro266
website: http://forums.bukkit.org/threads/39672/
main: com.thezorro266.simpleregionmarket.SimpleRegionMarket
depend: [WorldGuard]

commands:
  regionmarket:
    description: Using Simple Region Market
    aliases: rm
    usage: /regionmarket ? | list | maxregions | lang

permissions:
  simpleregionmarket.*:
    description: Admin commands, Buying/Selling regions
    children:
      simpleregionmarket.admin: true
      simpleregionmarket.buy: true
      simpleregionmarket.sell: true
  simpleregionmarket.admin:
    default: op
  simpleregionmarket.buy:
    default: false
  simpleregionmarket.sell:
    default: false