name: ${project.name}
version: ${project.version}
author: theZorro266
website: ${project.url}
main: ${project.groupId}.${project.artifactId}.${project.name}
load: POSTWORLD
depend: ['WorldGuard']
softdepend: ['Vault', 'ChestShop']

commands:
  regionmarket:
    description: Using Simple Region Market
    aliases: rm
    usage: /regionmarket limits | list | version

permissions:
  simpleregionmarket.admin:
    description: Admin permissions
